def tr_rav(lenguaje, dato, **kwarg):

    data = {
        'es': {
            "comment": "[C]Comentario enviado. (っ•̀ω•̀)╮ =͟͟͞ 💗\n\n\n[C]Gracias por usar el\n[C]servicio de mensaje\n[C]Ravnin. (ง •᷄ω•)ว",
            "Id_Amino": f"El ID del link es: {kwarg.get('ID')}",
            "destacar": f"¡Post {kwarg.get('Titulo')} destacado con exito! >w<",
            "join": "Ya me uni al chat -w-",
            "one_love": f"Tienen un {kwarg.get('num')}% {kwarg.get('name')} y {kwarg.get('params')} parecen ser buenos amigos, a lo mejor en un futuro sean mejores amigos. OwO",
            "two_love": f"Tienen un {kwarg.get('num')}% {kwarg.get('name')} y {kwarg.get('params')} parecen ser buenos amigos, a lo mejor son coge amigos... O novios? OwO",
            "three_love": f"Tienen un {kwarg.get('num')}% {kwarg.get('name')} y {kwarg.get('params')}, probablemente conocidos... Pero lo muy seguro es que se odian, creeme. >.<",
            "four_loev": f"Tienen un {kwarg.get('num')}% {kwarg.get('name')} y {kwarg.get('params')}, son como la caca y comida, no van.. -n-",
            "purge": "<$Mensajes borrados con exito >:3$>",
            "kick": "<$¡Usuario rebelde expulsado del chat con exito! La proxima vez que vuelvas te metere mas patadas. Jum. uwu$>",
            "comunidad_like": "<$¡Ya puse esta comunidad como de mis favoritas en mi perfil global, muak! uwu$>",
            "kill": [
                f"Le agarra la cabeza {kwarg.get('params')}... Y zaz, lo mata a besitos en el poto",
                f"¡Empieza agarrarlo de los pies a {kwarg.get('params')} y lo manda por los aires!",
                f"Agarra un pan y ¡Oh no! no, no.. Suelta ese pan.. Mato a {kwarg.get('params')} >.<",
                f"Le mando un beso toxico a {kwarg.get('params')}... K.O x.x",
                f"Le recuerda a la ex y lo mata de tristeza a {kwarg.get('params')} u.u",
                f"Empieza a comerse de poco a poco a {kwarg.get('params')}, pero a besos.. @-@"
            ],
            "gey": f"Eres un {kwarg.get('rgay')}. Grr 6w6",
            "coin": "OMG; Que suertudo eres!!! >w<",
            "nalgada": [
                f"{kwarg.get('params')} le agarra fuertemente la colita a {kwarg.get('params')} uwu",
                f"{kwarg.get('params')} agarra su mano y la lleva al otro mundo para llevarla a este... Y darle una tremenda nalgada a {kwarg.get('params')} >:3",
                f"Que haces mi amooor {kwarg.get('params')}? *Le agarra una na       lgita* ve papasito'",
                f"{kwarg.get('params')} le da una nalgada a {kwarg.get('params')} y se va corriendo o.o",
            ],
            "sleep": [
                f"Hagamos la mimision, {kwarg.get('name')} -w-",
                f"Zzzz.... ¡¡Qué haces despertandome, {kwarg.get('name')}!! Agh -n-",
                f"Te espero en la camita, {kwarg.get('name')} pa' comerte a besos -w-"
                f"Mi-mimiendo con mi amado/a {kwarg.get('name')} uwu",
                f"¡Una nalgada y a mimir {kwarg.get('name')}! :3"
            ],
            "hug": f"<${kwarg.get('name')}$ abraza con mucho amor a <${kwarg.get('params')}$>... >w<",
            "kiss": f"<${kwarg.get('name')}$ besó apasionadamente a <${kwarg.get('params')}$>... >w<",
            "trivia": "[CB]• - ̗̀ ❛Esta es la lista de categorias sobre el juego trivia.‘﹏!˚ • '\n\n\n*ૢ                         ── lυv мe\n╰► ﹫Geografía\n╰► ﹫Ciencia\n╰► ﹫General\n╰► ﹫Arte\n\n[C]➤ Uso: -trivia Geografía",
            "casarse": [
                f"\t\tIglesia Ravnin.\n\n Hermanas y hermanos, estamos aquí reunidos para presenciar la boda de {kwarg.get('name')} y {kwarg.get('params')}. Si alguien se opone... Pues chinga su madre, no nos importa >:)",
                f"\t\tIglesia Ravnin.\n\n Hoy celebramos el santo matrimonio de {kwarg.get('name')} y {kwarg.get('params')}.\n\nAquel que se oponga a esta boda, caye ahora o vayase a ver netflix.",
                f"\t\tIglesia Ravnin.\n\n Con el poder de la matrix, yo declaró, casados a {kwarg.get('name')} y {kwarg.get('params')}. Puede besar al novio/a",
                f"\t\tIglesia Ravnin.\n\n Desde hoy, el amor entre {kwarg.get('name')} y {kwarg.get('params')}, queda bendecido por los de arriba."
            ],
            "patada": [
                f"Le mete una patada y lo manda por los aires a {kwarg.get('params')} >:3",
                f"Brr... Brrrrrr. Soy franshesco virgolini y yo, te mete una patade de tu de tu vida, {kwarg.get('params')}",
                f"Le mete una patada en las partes bajas... A {kwarg.get('params')} >.<",
                f"Le empieza a dar patadas como otaku a {kwarg.get('params')} -n-'",
                f"Le dio una pantada que lo deja sin hijos a {kwarg.get('params')} -n-"
            ],
            "desaparecer": [
                f"{kwarg.get('name')} desaparece como gil",
                f"{kwarg.get('name')} desaparece como nekito",
                f"{kwarg.get('name')} desaparece como furro",
                f"{kwarg.get('name')} desaparece como {kwarg.get('name')}, jaja k sad",
                f"{kwarg.get('name')} desaparece como fuckboy",
                f"{kwarg.get('name')} desaparece como fuckgirl",
                f"{kwarg.get('name')} se va por unos cigarros",
            ],
            "cry": [
                f"{kwarg.get('name')} empieza a llorar... >n<",
                f"{kwarg.get('name')} sus lagrimas caen de poco a poco por tanta tristeza u.u",
                f"{kwarg.get('name')} llora como furro, eso... Ya es triste",
                f"{kwarg.get('name')} Empieza a sentirse mal, se va a una esquinita, y empieza a llorar solito/a...",
                f"{kwarg.get('name')} todos sus miedos, sus debilidades, sus fracasos... Se los ahorro, pero ya no puede mas, y empieza a llorar.. u.u",
                f"{kwarg.get('name')} le caen lagrimas de felicidad >w<",
                f"{kwarg.get('name')} se pone rojito, y se pone tan feliz que llorar de.. ?¡Felicidad! OwO",
            ],
            "aparece": [
                f"{kwarg.get('name')} aparece como gil",
                f"{kwarg.get('name')} aparece como nekito",
                f"{kwarg.get('name')} aparece como furro",
                f"{kwarg.get('name')} aparece como {kwarg.get('name')}, jaja k sad",
                f"{kwarg.get('name')} aparece como fuckboy",
                f"{kwarg.get('name')} aparece como fuckgirl",
                f"{kwarg.get('name')} aparece con 3 hijos, y una vida de gil",
            ],
            "ship": [
                f"Oye {kwarg.get('name')}, si tú, deberias tener hijos con {kwarg.get('params')} -w-",
                "¡Qué haces perdiendo el tiempo, ya comanse!",
                f"Olvida a {kwarg.get('params')} mi casa esta desocupada, bb.",
                "Grr. Bebé, olvidala a ella, y ven conmigo, te hago ciberbebesbots.",
                f"{kwarg.get('name')} y {kwarg.get('params')}. Ya cansense. Si joden, comanse, no, ni comanse, vayan hagan un hijo.",
                f"Ñam ñam, ojala {kwarg.get('name')} y {kwarg.get('params')} fueran mis padres uwu",
                f"{kwarg.get('name')} y {kwarg.get('params')} son demasiado  goals para este mundo -w-"
            ],
            "sonrojar": [
                f"{kwarg.get('name')} Se empezo a sonrojar levemente.. >//<",
                f"La carita de {kwarg.get('name')} se pone como un tomatito ///",
                f"{kwarg.get('name')} empieza a estrecerse y a ponerse rojito/a >u<",
                f"Se tapa la carita de lo sonrojado/a que esta, {kwarg.get('name')} o///o"
            ],
            "saludo": [
                "Hakuna matata 〜(^∇^〜）", "Holis -w-", "namasté ＼（＠￣∇￣＠）／",
                "salamu alaykum (︶ω︶)", "Hello!!! (｡^‿^｡)", "konichiwa (●⌒∇⌒●)",
                "-Beso en las dos mejillas- muak, muak (≧▽≦)",
                "-Se besan en la boca como en la madre rusia- (´°̥̥̥﹏°̥̥̥ )人(´°̥̥̥ω°̥̥̥｀)",
                "-Chocan narizes- el aliento de la vida!! (((o(ﾟ▽ﾟ)o)))",
                "mano po!!", "-Se abrazan- (/□＼*)・゜ "
            ],
            "correr": [
                "Empieza a correr como gil", "Se fue",
                "Se corr.. Digo, se fue corriendo a por un cafesito>:3",
                "-c va lentamente-",
                "Empieza a correr super rapido... Nadie, lo detiene, sigue corriendo,empieza a correr.. Ya enserio, sal de tu casa y ve a correr de verdad. -w-",
                "Soy franshesco Virgo-lini y soy el autok ma rapidko del planita tirr4"
            ],
            "vir_kiss": f"{kwarg.get('name')} besó apasionadamente a {kwarg.get('params')}...",
            "vir_meter": f"El Dios todo poderoso {kwarg.get('name')} is going va a desactivarme metiendome un {kwarg.get('params')}...",
            "vir_lick": f"{kwarg.get('name')} lame a {kwarg.get('params')}...",
            "vir_kiss": f"{kwarg.get('name')} empieza a darle puñetazos a {kwarg.get('params')}... >:D",
            "vir_hit": f"{kwarg.get('name')} baneó del chat a {kwarg.get('params')}...",
            "leave": f"[C]¡Gracias por tenerme en este chat, pero ya me tengo ir a descansar! >w<",
            "owner_off": "Ño eres mi dueño, ¿Qué haces usando este comando? -.-'",
            "owner_error": "<$[C]¡Error, pon bien el comando tontito/a! -w-\n\n[C]Recuerda poner -help -comando para saber como usarlo uwu$>",
            "ban": "<$¡Usuario baneado con exito! owo'$>",
            "warn": "<$¡Usuario con advertencia con exito! owo'$>",
            "invite_chat": "<$¡Now they can invite in chat! uwu$>",
            "invite_chat_none": "<$¡No no one can invite in chat! uwu$>",
            "chat_view": "<$Ahora puedes leer el chat! uwu$>",
            "chat_title": "<$¡changed chat title changed! uwu$>",
            "block": "<$Usuario bloqueado con exito! owo$>",
            "chat_content": "<$Biografia de chat cambiada! uwu$>",
            "chat_anuncio": "<$¡Anuncio cambiado del chat! uwu$>",
            "unlock": "<$Usuario desbloqueado con exito! owo$>",
            "strike": "<$¡Usuario con falta con exito! owo$>",
            "burbuja": "Your chat bubble was successfully changed! :3",
            "chat_fij": "<$¡Anuncio fijado del chat! uwu$>",
            "chat_fij_none": "<$¡Anuncio desfijado del chat! uwu$>",
        },

        'pt': {
            "comment": "[C]Comentario enviado. (っ•̀ω•̀)╮ =͟͟͞ 💗\n\n\n[C]Obrigado por usar o\n[C]Nosso serviço de mensagem\n[C]Haha. ",
            "Id_Amino": f"O id do link é: {kwarg.get('ID')}",
            "destacar": f"¡Post {kwarg.get('Titulo')} destacado com sucesso! >w<",
            "join": "Entrei nele -w-",
            "one_love": f"Tem {kwarg.get('num')}% {kwarg.get('name')} e {kwarg.get('params')} parecem serem bons amigos, ou melhor, quase noivos...",
            "two_love": f"Tem {kwarg.get('num')}% {kwarg.get('name')} e {kwarg.get('params')} Parecem ser bons amigos, Ou melhor... há quantos anos estão casados?OwO",
            "three_love": f"Tem {kwarg.get('num')}% {kwarg.get('name')} e {kwarg.get('params')}, provavelmente conhecidos... mas estou segura de que se odeiam, briguem. >.<",
            "four_loev": f"Tem {kwarg.get('num')}% {kwarg.get('name')} e {kwarg.get('params')}, é igual agua e comida, não se dão... -n-",
            "purge": "<$Mensagem apagada com sucesso>:3$>",
            "kick": "<$Usuario rebelde expulsado do chat com sucesso! a proxima vez que voltar te meterei porradas! uwu$>",
            "comunidad_like": "<$Já coloquei esta comunidade como minha favorita no perfil global$>",
            "kill": [
                f"agarrei pela cabeça {kwarg.get('params')}... e zazzzz, te mato enforcado com minha bengala",
                f"começa agarrando pelos pés {kwarg.get('params')} e o manda pelos ares",
                f"Chamo um hacker... ele trava a {kwarg.get('params')} >.<",
                f"Mando um beijo falso para {kwarg.get('params')}... iludido novamente, K.O. x.x",
                f"Se recorda da sua ex e o mata de tristeza {kwarg.get('params')} u.u",
                f"começa a o devorar pouco a pouco {kwarg.get('params')}, tem gosto de frango... @-@"
            ],
            "gey": f"Teste feito pelo ratin {kwarg.get('rgay')}. ihhhh 6w6",
            "coin": "OMG; Que sortudo!!!! >w<",
            "nalgada": [
                f"{kwarg.get('params')} agarra com força a cabeça de {kwarg.get('params')}",
                f"{kwarg.get('params')} casa-se com ele, vivem 10 anos felizes e o espanca {kwarg.get('params')} >:3",
                f"O que está fazendo meu amor? {kwarg.get('params')}? *sobe no seu colo* papai @-@",
                f"{kwarg.get('params')} Dá uma bicuda em {kwarg.get('params')} e sai correndo o.o",
            ],
            "sleep": [
                f"Vamos dormir juntinhos? {kwarg.get('name')} -w-",
                f"Zzzz.... O que está fazendo acordado? {kwarg.get('name')}!! Agh -n-",
                f"Te espero na caminha, {kwarg.get('name')} Vou te encher de beijos -w-"
                f"Mimindo com meu amado/a {kwarg.get('name')} uwu",
                f"Te dou um chute dormindo {kwarg.get('name')}! :3"
            ],
            "hug": f"<${kwarg.get('name')}$ abraça você com muito amor <${kwarg.get('params')}$>... >w<",
            "kiss": f"<${kwarg.get('name')}$ Beijou pique kid bengala em <${kwarg.get('params')}$>... >w<",
            "trivia": "[CB]• - ̗̀ ❛Lista de categoria sobre o trivia.‘﹏!˚ • '\n\n\n*ૢ                         ── lυv мe\n╰► ﹫Geografía\n╰► ﹫Ciencia\n╰► ﹫General\n╰► ﹫Arte\n\n[C]➤ Uso: -trivia Geografía",
            "casarse": [
                f"\t\tIglesia Ravnin.\n\n irmãos e irmãs, estamos aqui reunidos para presenciar a união de {kwarg.get('name')} e {kwarg.get('params')}. se alguém é contra... vai se ferrar, a gente não se importa >:)",
                f"\t\tIglesia Ravnin.\n\n hoje celebramos o santo matrimonio de {kwarg.get('name')} e {kwarg.get('params')}.\n\n aquele que é contra a esta união, vá assistir faustão.",
                f"\t\tIglesia Ravnin.\n\n Com o poder de la matrix, eu o declaro, casados {kwarg.get('name')} e {kwarg.get('params')}. Pode beijar ao noivo/a",
                f"\t\tIglesia Ravnin.\n\n desde hoje, o amor entre {kwarg.get('name')} e {kwarg.get('params')}, está sendo abençoado pelo de cima."
            ],
            "patada": [
                f"Te mete um chute e o manda pelos ares {kwarg.get('params')} >:3",
                f"Brr... Brrrrrr. Soy franshesco virgolini e eu, eu comi a sua primaa {kwarg.get('params')}",
                f"Dá um chute em suas partes baixas... {kwarg.get('params')} >.<",
                f"Começa a dar chutes nesse otaku {kwarg.get('params')} -n-'",
                f"te dou um chute nas partes intimas que o deixa sem filhos {kwarg.get('params')} -n-"
            ],
            "desaparecer": [
                f"{kwarg.get('name')} desaparece como seu pai",
                f"{kwarg.get('name')} desaparece como flash",
                f"{kwarg.get('name')} desaparece como furry",
                f"{kwarg.get('name')} desaparece como {kwarg.get('name')}, jaja sad",
                f"{kwarg.get('name')} desaparece como fuckboy",
                f"{kwarg.get('name')} desaparece como fuckgirl",
                f"{kwarg.get('name')} foi comprar cigarros",
            ],
            "cry": [
                f"{kwarg.get('name')} está chorando... >n<",
                f"{kwarg.get('name')} suas lagrimas cai de pouco a pouco u.u",
                f"{kwarg.get('name')} chora igual furry bombado, isso... ja é triste",
                f"{kwarg.get('name')} começa a sentir mal, vai na esquina, e depois começa a chorar sozinho/a...",
                f"{kwarg.get('name')} todos seus medos, suas debilidades, seus fracassos... Se passou, mas já não pode mais, e começa a chorar.. u.u",
                f"{kwarg.get('name')} cai suas lagrimas de felicidade >w<",
                f"{kwarg.get('name')} está tão roxo, e está tão feliz que começou a chorar.. ?¡Felicidade! OwO",
            ],
            "aparece": [
                f"{kwarg.get('name')} aparece como batman",
                f"{kwarg.get('name')} aparece como flash",
                f"{kwarg.get('name')} aparece como furry",
                f"{kwarg.get('name')} aparece como {kwarg.get('name')}, jaja sad",
                f"{kwarg.get('name')} aparece como fuckboy",
                f"{kwarg.get('name')} aparece como fuckgirl",
                f"{kwarg.get('name')} aparece com 3 filhos furrys, e uma vida de amino user",
            ],
            "ship": [
                f"oi {kwarg.get('name')}, você deveria deveria ter filhos com {kwarg.get('params')} -w-",
                "O que faz perdendo tempo? hahah, já se comam!",
                f"Ei {kwarg.get('params')} minha casa esta desocupada, bb.",
                "Grr. bebê, deixe ela, e venha comigo, te faço ciberbebesbots.",
                f"{kwarg.get('name')} e {kwarg.get('params')}. já casense. Marquem encontros, se comam, não, não se comam, façam muitoosss filhos.",
                f"Ñam ñam, você {kwarg.get('name')} e {kwarg.get('params')} foram meus padres uwu",
                f"{kwarg.get('name')} e {kwarg.get('params')} são muito  fofos para este mundo -w-"
            ],
            "sonrojar": [
                f"{kwarg.get('name')} Começa a ficar vermelho lentamente... >//<",
                f"A cara de {kwarg.get('name')} começa a ficar roxa ///",
                f"{kwarg.get('name')} começa a se estressar  e depois fica roxo/a >u<",
                f"Tapa sua cara de tão roxo que está, {kwarg.get('name')} o///o"
            ],
            "saludo": [
                "Hakuna matata 〜(^∇^〜）", "Holis -w-", "namasté ＼（＠￣∇￣＠）／",
                "salamu alaykum (︶ω︶)", "Hello!!! (｡^‿^｡)", "konichiwa (●⌒∇⌒●)",
                "-Beso en las dos mejillas- muak, muak (≧▽≦)",
                "-Se besan en la boca como en la madre rusia- (´°̥̥̥﹏°̥̥̥ )人(´°̥̥̥ω°̥̥̥｀)",
                "-Chocan narizes- el aliento de la vida!! (((o(ﾟ▽ﾟ)o)))",
                "mano po!!", "-Se abrazan- (/□＼*)・゜ "
            ],
            "correr": [
                "Empieza a correr como gil", "Se foi",
                "se fod.. Digo, se foi correndo para preparar um café>:3",
                "-c vai lentamente-",
                "começa a correr super rapido... nada,nada o segura, segue correndo, começa a correr.. é serio, sai de tua casa e vai correr de verdade. -w-",
                "Soy franshesco Virgo-lini y soy el autok ma rapidko del planita tirr4"
            ],
            "vir_kiss": f"{kwarg.get('name')} beijou aproximadamente a {kwarg.get('params')}...",
            "vir_meter": f"o Deus todo poderoso {kwarg.get('name')} vai o desativar {kwarg.get('params')}...",
            "vir_lick": f"{kwarg.get('name')} chama a {kwarg.get('params')}...",
            "vir_kiss": f"{kwarg.get('name')} começa a dar pancadas em {kwarg.get('params')}... >:D",
            "vir_hit": f"{kwarg.get('name')} baniu do chat a {kwarg.get('params')}...",
            "leave": f"[C]Valeu por me ter em este chat, mas já tenho que ir descansar, vamos Lee! >w<",
            "owner_off": "Não é meu dono, Por que está usando isso? -.-'",
            "owner_error": "<$[C]erro, coloque o comando certo! -w-\n\n[C]Lembre-se de por -help -comando para saber como usa-lo uwu$>",
            "ban": "<$Usuario banido com sucesso owo'$>",
            "warn": "<$ Tomou advertencia com sucesso! owo'$>",
            "invite_chat": "<$Agora eles podem convidar no chat! uwu$>",
            "invite_chat_none": "<$ Não! Não! pode-se convidar no chat! uwu$>",
            "chat_view": "<$Agora podem ler! uwu$>",
            "chat_title": "<$titulo do chat trocado. uwu$>",
            "block": "<$Usuario bloqueado com sucesso! agora ele vai ver... owo$>",
            "chat_content": "<$Biografia de chat trocada! uwu$>",
            "chat_anuncio": "<$Anuncio trocado do chat! uwu$>",
            "unlock": "<$Usuario desbloqueado com sucesso! Acho que aprendeu a lição owo$>",
            "strike": "<$Usuario avisado com sucesso! owo$>",
            "burbuja": "Seu balão de bate-papo foi alterado com sucesso! :3",
            "chat_fij": "<$Anuncio fixado!$>",
            "chat_fij_none": "<$ Anuncio retirado! uwu$>",
        },

        'en': {
            "comment": "[C]Comment sent. (っ-̀ω-̀)╮ =͟͟͞ 💗 \n\n\n[C]Thank you for using the \n[C]Ravnin message service. (ง -᷄ω-)ว",
            "Id_Amino": f"The ide of this link is: {kwarg.get('ID')}",
            "destacar": f"Post: {kwarg.get('Titulo')} successfully featured! >w<",
            "join": "I have already joinend the chat -w-",
            "one_love": f"hey have a {kwarg.get('num')}% {kwarg.get('name')} and {kwarg.get('params')} they seem to be good friends, maybe in the future they will be better friends. OwO",
            "two_love": f"They have a {kwarg.get('num')}% {kwarg.get('name')} and {kwarg.get('params')} they seem to be good friends, maybe they are friends ... or boyfriends? OwO",
            "three_love": f"They have a {kwarg.get('num')}% {kwarg.get('name')} and {kwarg.get('params')}, probably acquaintances ... But the very certain thing is that they hate each other, believe me. >.<",
            "four_love": f"They have a {kwarg.get('num')}% {kwarg.get('name')} and {kwarg.get('params')} they are like poop and food, they don't go.. -n-",
            "purge": "<$Ño eres mi dueño, ¿Qué haces usando este comando? -.-$>",
            "kick": "<$Rebel user kicked out of chat successfully!  Next time you come back I'll kick you more.. uwu$>",
            "comunindad_like": "<$¡I already put this community as one of my favorites in my global profile, muah! uwu$>",
            "kill": [
                f"He grabs his head {kwarg.get('params')} and arms, put him in the pot",
                f"Starts grabbing {kwarg.get('params')} by the feet and sends him flying!",
                f"Grab a loaf and oh no!  no, no .. Drop that bread .. I kill {kwarg.get('params')} >.<",
                f"I send a toxic kiss to {kwarg.get('params')}... K.O x.x",
                f"Reminds him of the ex and kills him with sadness {kwarg.get('params')} u.u",
                f"to eat {kwarg.get('params')} little by little, but with kisses.. @-@",
            ],
            "gey": f"You are  a {kwarg.get('rgay')} gay. WARWRRRRRRRR",
            "coin": "OMG; How lucky you are !!!",
            "nalgada": [
                f"{kwarg.get('name')}  grabs tightly the tail of {kwarg.get('params')}  uwu",
                f"{kwarg.get('name')} grabs her hand and takes her to the other world to take her to this ... and give a tremendous spanking {kwarg.get('params')} >:3",
                f"What are you doing {kwarg.get('params')}?   Grabs a butt  go daddy'",
                f"{kwarg.get('name')}  he spanks {kwarg.get('params')} and runs off o.o",
            ],
            "sleep": [
                f"Let's do the mimision, {kwarg.get('name')} -w-",
                f"Zzzz.... What are you doing? waking me up, {kwarg.get('name')} !!  Agh -n-",
                f"I'll wait for you on the bed, {kwarg.get('name')} to eat you with kisses -w-"
                f"pampering with my beloved/a {kwarg.get('name')} uwu",
                f"A spanking and pampering {kwarg.get('name')}! :3"
            ],
            "hug": f"<${kwarg.get('name')}$ embraces with much love <${kwarg.get('params')}$>... >w<",
            "kiss": f"<${kwarg.get('name')}$> passionately kissed <${kwarg.get('params')}$>... >w<",
            "trivia": "[CB]• - ̗̀ ❛This is the list of categories about the trivia game.‘﹏!˚ • '\n\n\n*ૢ                         ── drone\n╰► ﹫Geography\n╰► ﹫Math\n╰► ﹫General\n╰► ﹫Art\n\n[C]➤ Uso: -trivia Geography",
            "casarse": [
                f"\t\t 𝐃𝐫𝐨𝐧𝐞𝐗 \n\n Sisters and brothers, we are gathered here to witness the wedding of {kwarg.get('name')} and {kwarg.get('params')}.  If someone objects ... Well, fuck his mother, we don't care >:)",
                f"\t\t 𝐃𝐫𝐨𝐧𝐞𝐗.\n\n Today we celebrate the holy marriage of {kwarg.get('name')} and {kwarg.get('params')}. \n\n Whoever opposes this wedding, falls now or goes to see Netflix.",
                f"\t\t 𝐃𝐫𝐨𝐧𝐞𝐗.\n\n With the power of the matrix, I declared, married to {kwarg.get('name')} and {kwarg.get('params')}.  You can kiss the boyfriend / girlfriend",
                f"\t\t 𝐃𝐫𝐨𝐧𝐞𝐗.\n\n From today, the love between {kwarg.get('name')} and {kwarg.get('params')}, is blessed by those above."
            ],
            "patada": [
                f"He kicks him and sends him flying into the air {kwarg.get('params')} >:3",
                f"Brr... Brrrrrr.I am 𝐃𝐫𝐨𝐧𝐞𝐗 and I,  put a scar of your life, {kwarg.get('params')}",
                f"Kicks him in the lower parts ...  {kwarg.get('params')} >.<",
                f"He starts to kick like otaku at {kwarg.get('params')} -n-'",
                f"He gave a pantada that leaves him childless {kwarg.get('params')} yny"
            ],
            "desaperecer": [
                f"{kwarg.get('name')} disappear like gil",
                f"{kwarg.get('name')} disappear like nekito",
                f"{kwarg.get('name')} disappear like furro",
                f"{kwarg.get('name')} disappear like {kwarg.get('params')}, jaja k sad",
                f"{kwarg.get('name')} disappear like fuckboy",
                f"{kwarg.get('name')} disappear like fuckgirl",
                f"{kwarg.get('name')} he goes for some cigarettes",
            ],
            "cry": [
                f"{kwarg.get('name')} Begin to cry... >n<",
                f"{kwarg.get('name')} her tears fall little by little for so much sadness u.u",
                f"{kwarg.get('name')} cries like a furious, that ... is already sad",
                f"{kwarg.get('name')} He starts to feel bad, he goes to a corner, and he starts crying on his own...",
                f"{kwarg.get('name')} all his fears, his weaknesses, his failures ...,  he can't take it anymore, and he starts to cry.. u.u",
                f"{kwarg.get('name')} tears of happiness fall >w<",
                f"{kwarg.get('name')} he turns red, and he gets so happy that he cries about ...? Happiness! OwO",
            ],
            "aparece": [
                f"{kwarg.get('name')} appears as gil",
                f"{kwarg.get('name')} appears as nekito",
                f"{kwarg.get('name')} appears as furro",
                f"{kwarg.get('name')} appears as {kwarg.get('name')}, jaja k sad",
                f"{kwarg.get('name')} appears as fuckboy",
                f"{kwarg.get('name')} appears as fuckgirl",
                f"{kwarg.get('name')} appears with 3 children, and a life of gil",
            ],
            "ship": [
                f"Hey {kwarg.get('name')}, if you, you should have children with {kwarg.get('params')} -w-",
                "What are you doing wasting time, eat now!",
                f"Forget {kwarg.get('params')} my house is unoccupied, bb.",
                "Grr. Bebé, forget her, and come with me, I make you my babe.",
                f"{kwarg.get('name')} and {kwarg.get('params')}.  Get tired.  If they fuck, eat, no, or eat, go make a child.",
                f"Yum yum, I hope you {kwarg.get('name')} and {kwarg.get('params')} were my parents uwu",
                f"{kwarg.get('name')} and {kwarg.get('params')} are too good for this world -w-"
            ],
            "sonrojar": [
                f"{kwarg.get('name')} He started to blush slightly.. >//<",
                f"{kwarg.get('name')} face turns like an apple ///",
                f"{kwarg.get('name')} begins to narrow and turn red >u<",
                f"He covers his face because of how red he is,, {kwarg.get('name')} o///o"
            ],
            "saludo": [
                "Hakuna matata 〜 (^ ∇ ^ 〜）", "Holis -w-", "namasté ＼ （＠ ￣∇￣ ＠） ／",
                "salamu alaykum (︶ω︶)", "Hello !!! (｡ ^ ‿ ^｡)", "konichiwa (● ⌒∇⌒ ●)",
                "-Kiss on both cheeks- muak, muak (* ≧ ▽ ≦)",
                "-  - (* ´ ° ̥̥̥﹏ ° ̥̥̥) 人 (´ ° ̥̥̥ω ° ̥̥̥ ｀)",
                "-Chocan noses- the breath of life !! (((o (* ﾟ ▽ ﾟ *) o)))",
                "hand po !!", "-They embrace- (/ □ ＼ *) ・゜ "
            ],
            "correr": [
                "Start running like gil", "He left",
                "He ran ... I mean, he ran for a little coffee>: 3",
                "-c goes slowly-",
                "He starts running super fast ... Nobody stops him, keeps running, starts running .. Really, get out of your house and go run for real. -W-"
            ],
            "vir_kiss": f"{kwarg.get('name')} passionately kissed {kwarg.get('params')}...",
            "vir_meter": f"Almighty God {kwarg.get('name')} is going to desactivate me by giving me a {kwarg.get('params')}...",
            "vir_lick": f"{kwarg.get('name')} the lame a {kwarg.get('params')}...",
            "vir_hit": f"{kwarg.get('name')} starts punching {kwarg.get('params')}... >:D",
            "vir_ban": f"{kwarg.get('name')} banned from chat {kwarg.get('params')}...",
            "leave": f"[C]¡Thanks for having me in this chat, but now I have to go to rest! >w<",
            "ban": "<$User successfully banned! owo'$>",
            "warn": "<$User warned successfully! owo'$>",
            "owner_off": "<$You don't own me, what are you doing using this command? -.-'",
            "invite_chat": "<$Now they can invite in chat! uwu$>",
            "invite_chat_none": "<$No no one can invite in chat! uwu$>",
            "chat_view": "<$Now you can read chat! uwu$>",
            "chat_title": "<$Changed chat title changed! uwu$>",
            "block": "<$User successfully blocked! owo$>",
            "chat_content": "<$Changed chat biography changed! uwu$>",
            "chat_announcement": "<$Changed chat announcement! uwu$>",
            "unlock": "<$User successfully unlocked! owo$>",
            "strike": "<$User successfully fouled! owo$>",
            "bubble": "Your chat bubble was successfully changed! :3",
            "chat_fij": "<$Advertisement fixed from chat! uwu$>",
            "chat_fij_none": "<$Chat ad unset! uwu$>",
            "owner_error": "<$[C]Error, get the command right dummy! -w-[C]Remember to put -help -command to know how to use it uwu$>",
        }
    }
    return data[lenguaje][dato]
